image: phpunit/phpunit:6.0.6

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
         - apk add --no-cache php7-gd php7-xmlwriter
         - php -r "file_exists('.env') || copy('.env.example', '.env');"
         - composer install
         - php artisan key:generate
         - php artisan passport:install --force
         - phpunit
        services:
          - mongodb
definitions:
  services:
    mongodb:
      image: mongo

